import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)
import java.awt.Color;

/**
 * This class makes a word object with a given string and colour, 
 * and then moves it across the screen. It gets deleted
 * from the world when it reaches the edge.
 * 
 * @author Alex, Kathy, Alina 
 * @version November 9th, 2017
 */
public class Word extends Actor
{
    //the word itself, as text
    private String word;
    //speed with which word object moves across screen
    private static int speed;

    // constructor gets the string and fill colour of the box around the word, then sets that as the 
    // image for this word object
    public Word(String text, Color co)
    {
        word = text;
        // display the random word generated by the WordGenerator class
        GreenfootImage outImage = new GreenfootImage(text, 20 , Color.BLACK, co); 
        this.setImage(outImage);
    }

    public void act()
    { 
        moveWord(); // move word a little bit for each act
    }

    // this method makes the word move
    public void moveWord()
    {
        // add the speed (per frame) to the x coordinate of the word
        setLocation(getX() + speed, getY());

        // if the word is at the edge of the window
        if(getX() > getWorld().getWidth()-5){
            //delete the word object from the hashmap (of String-Object pairs)
            WordObjects.words.remove(word);
            //delete word object from world
            getWorld().removeObject(this);
        }
    }

    // this method sets the speed to how many pixels the word should move per frame
    public static void setSpeed(int pixels) {
        speed = pixels;
        //speed cannot be less than 1 pixel per frame
        if(speed < 1)
            speed = 1;
    }

    // this method returns the length of the word
    public int getWordLength()
    {
        return word.length();
    }

    // this method returns the word string
    public String getString()
    {
        return word;
    }
}